call npm install axios@0.15.3
call npm install node-sass@4.5.3
call npm install sass-loader@6.0.3
call npm install body-parser@1.17.2
call npm install connect-flash@0.1.1
call npm install connect-mongo@1.3.2
call npm install cookie-parser@1.4.3
call npm install dompurify@0.8.5
call npm install dotenv@4.0.0
call npm install es6-promisify@5.0.0
call npm install express@4.15.2
call npm install express-session@1.15.1
call npm install express-validator@3.1.2
call npm install faker@4.1.0
call npm install forever@0.15.3
call npm install glob@7.1.1
call npm install gulp-sass@3.1.0
call npm install html-to-text@3.2.0
call npm install jimp@0.2.27
call npm install juice@4.0.2
call npm install md5@2.2.1
call npm install moment@2.17.1
call npm install mongoose@4.8.7
call npm install mongoose-mongodb-errors@0.0.2
call npm install multer@1.3.0
call npm install node-gyp@3.6.2
call npm install nodemailer@3.1.5
call npm install nw-gyp@3.4.0
call npm install passport@0.3.2
call npm install passport-local@1.0.0
call npm install passport-local-mongoose@4.0.0
call npm install pug@2.0.0-beta6
call npm install python@0.0.4
call npm install python2@0.0.1
call npm install slugs@0.1.3
call npm install uuid@3.0.1
call npm install validator@7.0.0
call npm install autoprefixer@6.7.7
call npm install babel-core@6.24.0
call npm install babel-loader@6.4.0
call npm install babel-preset-es2015@6.24.0
call npm install concurrently@3.4.0
call npm install css-loader@0.27.3
call npm install extract-text-webpack-plugin@2.1.0
call npm install nodemon@1.11.0
call npm install postcss-loader@1.3.3
call npm install webpack@2.2.1
pause