
version: "3.3"
services:
  mongodb:
    image: mongo:latest
    ports:
        - "127.0.0.1:27017:27017"
    env_file:
      - variables.env
    networks:
      - deliciousnet
  node:
    image: delicious:0.1.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7777:7777"
    env_file: 
      - variables.env
    volumes: 
      - ./app:/delicious/app
    networks:
      - deliciousnet
networks:
  deliciousnet:
    driver: bridge